home/urls.py
from . import views
from django.urls import path, include
app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

room/urls.py
from . import views
from django.urls import path, include
app_name = 'room'
urlpatterns = [
    path('', views.room, name="room"),
    path('room/<str:pk>/', views.detail, name="detail"),
    path('create-room/', views.createRoom, name="createroom"),
    path('update/<str:pk>/', views.updateRoom, name="update"),
    path('del/<str:pk>/', views.delRoom, name="del"),
    path('del-mess/<str:pk>/', views.delCMT, name="delmess"),
    path('room_topic/', views.topicRoom, name="topicRoom"),
]

test7tieng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('room/', include('room.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from . import views
from django.urls import path, include
app_name = 'user'
urlpatterns = [
    path('', views.user, name="user"),
    path('pro/<str:pk>/', views.profile, name="profile"),
]

home/models.py
from django.db import models

# Create your models here.

room/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    descreption = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True) 

    class Meta:
        ordering = ['-update', '-create']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.room.name

user/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from room.models import Topic

# Create your views here.
def home(request):
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request,  'home/home.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/')

def loginPage(request):
    page = 'login'
    if(request.user.is_authenticated):
        return redirect('/')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, 'User does not exist')
        user = authenticate(request, username=username, password = password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Username OR Password does not exist')
    context = {'page':page}
    return render(request,  'user/login_register.html', context)

def registerPage(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit= False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Error')
    return render(request,  'user/login_register.html', {'form':form})

room/views.py
from django.db.models import CharField
from django.db.models import Q
from django.shortcuts import render, redirect
from .models import Room, Message
from django.http import HttpResponse
from .roomform import RoomForm
from django.contrib.auth.decorators import login_required
# Create your views here.
#rooms = Room.objects.all()
def room(request):
    rooms = Room.objects.all()
    context = {'rooms':rooms}
    return render(request,  'room/room.html', context)

def detail(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all().order_by('-created')
    participants = room.participants.all()
    if request.method == 'POST':
        message = Message.objects.create(
            user= request.user,
            room = room,
            body =request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room:detail', pk = room.id)
    context = {'room':room, 'messages':room_messages, 'participants':participants}
    return render(request,  'room/roomdetail.html', context)

@login_required(login_url='/login')
def createRoom(request):
    form = RoomForm()
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request, 'room/roomform.html', context)

@login_required(login_url='/login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.user != room.host:
        return HttpResponse('You are not allowed here!!')

    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request, 'room/roomform.html', context)

@login_required(login_url='/login')
def delRoom(request, pk):
    room = Room.objects.get(id=pk)
    context = {'obj':room}

    if request.user != room.host:
        return HttpResponse('You are not allowed here!!')
    if request.method == 'POST':
        room.delete()
        return redirect('/')
    return render(request, 'room/delroom.html', context)

@login_required(login_url='/login')
def delCMT(request, pk):
    mess = Message.objects.get(id=pk)
    context = {'obj ':mess}

    if request.user != mess.user:
        return HttpResponse('You are not allowed here!!')
    if request.method == 'POST':
        mess.delete()
        return redirect('/')
    return render(request, 'room/delroom.html', context)

def topicRoom(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(descreption__icontains=q)
    )
    context = {'rooms':rooms}
    return render(request,  'room/room.html', context)

user/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

# Create your views here.
def user(request):
    context = {'user':request.user}
    return render(request,  'user/user.html', context)

def profile(request, pk):
    user = User.objects.get(id=pk)
    context = {'user':user}
    return render(request,  'user/user.html', context)

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type = "text/css" media='screen' href="{% static 'main.css'%}">
</head>
<body>
	
	{% include 'base/navbar.html' %}
	{% comment %} <ul class = "messages">
		{% for message in messages%}
		<li >{{message.tag}}</li>
		{%endfor%}
	</ul> {% endcomment %}
	<style>
		.content{
			display: grid;
			grid-template-columns: 1fr 3fr;
		}
	</style>
	<div class = "content">
		
		<div class = "menu">
			<ul>
				<li><a href="{% url 'home:home'%}">Home</a></li>
				<li><a href="{% url 'room:room'%}">Room</a></li>
				<li><a href="{% url 'user:user'%}">User</a></li>
			</ul>
		</div>
		<div>
			{% block content  %}
	
	
			{% endblock  %}
		</div>
	</div>
</body>
</html>

templates/base/navbar.html
<a href="">
    <h1>LOGO</h1>
</a>

<form action="{% url 'room:topicRoom' %}" method = "GET">
    <input type="text" name = "q" placeholder = "Search rooms...."/>
</form>

{% if request.user.is_authenticated %}
<p>Hello {{request.user}}</p>
<a href="{% url 'home:logout' %}">Logout</a>
{% else %}
<a href="{% url 'home:login' %}">Login</a>
{% endif %}
<hr>

templates/home/home.html
{% extends 'base/base.html' %}
{% block title %}Home{% endblock  %}

{% block content %}
	<h2>this is a home</h2>
	<div>
		<h3>Browse Topic</h3>
		<hr>
		{% for topic in topics %}
			<div>
				<a href = "{% url 'room:topicRoom' %}?q={{topic.name}}">{{topic.name}}</a>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/room/delroom.html
{% extends 'base/base.html' %}
{% block title %}Add Form{% endblock  %}

{% block content %}
	<h1>Confirm</h1>
	<div>
        <form action="" method="POST">
            {% csrf_token %}
            <p> Are you sure want to delete "{{obj}}" ?</p>
            <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
            <input type="submit" value = "Confirm">
        </form>
	</div>
{% endblock %}

templates/room/room.html
{% extends 'base/base.html' %}
{% block title %}Room{% endblock  %}

{% block content %}
	<h2>this is a room</h2>
	<h5>{{rooms.count}} rooms avaiable</h5>
	<a href="{% url 'room:createroom'%}">Create Room</a>
	<div>
		{% for room in rooms %}
			<div>
				<a href = "{% url 'room:detail' room.id%}">{{room.id}} -- {{room.name}}</a>
				{% if request.user == room.host %}
					<a href="{% url 'room:update' room.id%}">--Edit</a>
					<a href="{% url 'room:del' room.id%}">--Del</a>
				{% endif%}
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/room/roomdetail.html
{% extends 'base/base.html' %}
{% block title %}Room Detail{% endblock  %}

{% block content %}
	<style>
		.room-container{
			display: grid;
			grid-template-columns: 3fr 1fr;
		}
	</style>
	<div class = "room-container">
		<div>
			<div>
				<a href = "{% url 'user:profile' room.host.id%}">@{{room.host.username}}</a>
				<h2>{{room.name}}</h2>
				<small>{{room.topic.name}}</small>
				<p>{{room.descreption}}</p>
			</div>
		
			<div class="comment-wrapper">
				<h3>Conversation</h3>
				<hr>
		
				{% for message in messages%}
					<div>
						{% if request.user == message.user%}
							<a href="{% url 'room:delmess' message.id%}">Delete</a>
						{%endif%}
						<small>@{{message.user}}   {{message.created|timesince}}</small>
						<p>{{message.body}}</p>
					</div>
				{% endfor %}
			</div>
			
			{% if request.user.is_authenticated %}
				<div class="comment-form">
					<form action="" method = "POST">
						{% csrf_token %}
						<input type="text" name = "body" placeholder = "Your comment">
					</form>
				</div>
			{%endif%}
		</div>

		<div>
			<h3>Participants</h3>
			<hr>

			{% for user in participants%}
				<div>
					<p>@{{user.username}}</p>
				</div>
			{%endfor%}
		</div>
	</div>
{% endblock %}

templates/room/roomform.html
{% extends 'base/base.html' %}
{% block title %}Add Form{% endblock  %}

{% block content %}
	<h1>Add</h1>
	<div>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value = "submit">
        </form>
	</div>
{% endblock %}

templates/user/login_register.html
{% extends 'base/base.html' %}
{% block title %}Register{% endblock  %}

{% block content %}
    {%if page == 'login'%}
        <div>
            <form action="" method="POST">
                {% csrf_token %}

                <label >Username: </label>
                <input type="text" name="username" placeholder = "Enter User"/>
            </br>
                <label >Password: </label>
                <input type="password" name="password" placeholder = "Enter Password"/> 

                {% comment %} <label >UserName: </label>
                <input type="text" value="username" placeholder = "Enter User"/>  {% endcomment %}

                <input type = "submit" value = "Login"/>
                <p>Haven't signed up yet?</p>
                <a href="{% url 'home:register'%}">Register</a>
            </form>
        </div>
    {%else%}
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type = "submit" value = "Register"/>
            </form>
            <p>Already signed up yet?</p>
            <a href="{% url 'home:login' %}">Login</a>
        </div>
    {%endif%}
{% endblock %}

templates/user/user.html
{% extends 'base/base.html' %}
{% block title %}User{% endblock  %}

{% block content %}
	<h1>{{user.username}}</h1>

	<div class="profile-container">
		<div>
			Test
		</div>

		<div>

		</div>

		<div>

		</div>
	</div>
{% endblock %}